export const countryCodes: Record<string, string> = {
  'México': 'mx',
  'África do Sul': 'za',
  'Coreia do Sul': 'kr',
  'Coréia do Sul': 'kr',
  'Canadá': 'ca',
  'Estados Unidos': 'us',
  'EUA': 'us',
  'Paraguai': 'py',
  'Catar': 'qa',
  'Brasil': 'br',
  'Brazil': 'br',
  'Marrocos': 'ma',
  'Morocco': 'ma',
  'Haiti': 'ht',
  'Escócia': 'gb-sct',
  'Scotland': 'gb-sct',
  'Austrália': 'au',
  'Australia': 'au',
  'Alemanha': 'de',
  'Germany': 'de',
  'Curaçau': 'cw',
  'Curaçao': 'cw',
  'Holanda': 'nl',
  'Netherlands': 'nl',
  'Japão': 'jp',
  'Japan': 'jp',
  'Costa do Marfim': 'ci',
  'Ivory Coast': 'ci',
  'Equador': 'ec',
  'Ecuador': 'ec',
  'Tunísia': 'tn',
  'Tunisia': 'tn',
  'Espanha': 'es',
  'Spain': 'es',
  'Cabo Verde': 'cv',
  'Cape Verde': 'cv',
  'Bélgica': 'be',
  'Belgium': 'be',
  'Egito': 'eg',
  'Egypt': 'eg',
  'Arábia Saudita': 'sa',
  'Saudi Arabia': 'sa',
  'Uruguai': 'uy',
  'Uruguay': 'uy',
  'Irã': 'ir',
  'Iran': 'ir',
  'Nova Zelândia': 'nz',
  'New Zealand': 'nz',
  'França': 'fr',
  'France': 'fr',
  'Senegal': 'sn',
  'Noruega': 'no',
  'Norway': 'no',
  'Argentina': 'ar',
  'Argélia': 'dz',
  'Algeria': 'dz',
  'Áustria': 'at',
  'Austria': 'at',
  'Jordânia': 'jo',
  'Jordan': 'jo',
  'Portugal': 'pt',
  'Inglaterra': 'gb-eng',
  'England': 'gb-eng',
  'Croácia': 'hr',
  'Croatia': 'hr',
  'Gana': 'gh',
  'Ghana': 'gh',
  'Panamá': 'pa',
  'Panama': 'pa',
  'Uzbequistão': 'uz',
  'Uzbekistan': 'uz',
  'Colômbia': 'co',
  'Colombia': 'co',
  'Gales': 'gb-wls',
  'Wales': 'gb-wls',
  'Polônia': 'pl',
  'Poland': 'pl',
  'Dinamarca': 'dk',
  'Denmark': 'dk',
  'Costa Rica': 'cr',
  'Camarões': 'cm',
  'Cameroon': 'cm',
  'Sérvia': 'rs',
  'Serbia': 'rs',
  'Suíça': 'ch',
  'Switzerland': 'ch',
  'Nigéria': 'ng',
  'Nigeria': 'ng',
  'Ucrânia': 'ua',
  'Ukraine': 'ua',
  'Chile': 'cl',
  'Turquia': 'tr',
  'Turkey': 'tr',
  'Peru': 'pe',
  'Hungria': 'hu',
  'Hungary': 'hu',
  'Romênia': 'ro',
  'Romania': 'ro',
  'Itália': 'it',
  'Italy': 'it',
  'Suécia': 'se',
  'Sweden': 'se'
};

export const getFlagUrl = (countryName: string) => {
  const code = countryCodes[countryName];
  if (!code) return null;
  return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
};
